import axios from 'axios'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import { userAgent } from 'next/server'

import { fetchThemeConfig } from '~/data/theme-config'
import { $axios, apiClient } from '~/utils/api-client'

import PKG from '../package.json'
import './globals.css'
import { InitialDataProvider } from './providers'

const inter = Inter({ subsets: ['latin'] })

const fetchInitialData = async (headers: Headers) => {
  const userAgentObject = userAgent({
    headers,
  })

  $axios.defaults.headers.common['User-Agent'] =
    userAgentObject.ua + ` NextJS/v${PKG.dependencies.next} Kami/${PKG.version}`

  const tasks = [
    apiClient.aggregate.getAggregateData().then((data) => ({ ...data })),
    fetchThemeConfig(),
  ]
  // TODO error handle
  const [aggregateData, themeConfig] = await Promise.all(tasks).catch((err) => {
    console.log(err)
    return []
  })
  return {
    aggregateData,
    themeConfig,
  }
}

export async function generateMetadata() {
  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await fetchInitialData(headers())
  return (
    <html lang="zh-Hans">
      <InitialDataProvider data={data}>
        <body className={inter.className}>{children}</body>
      </InitialDataProvider>
    </html>
  )
}
